### ISSUE TITLE
Align: not enough memory for BAM sorting potentially due to BinsN too high

### ISSUE THREAD

**Issue by cpcouturier** [aristoteleo/dynast-release#3]
In the past, changing ulimit -Hn had fixed this. Now running this on Terra and this parameter is much more difficult to change. Changing the way BinsN is chosen or allowing an optional input to set it would be great!

![Screen Shot 2021-05-18 at 2 14 47 PM](https://user-images.githubusercontent.com/73311837/118837454-d698b480-b892-11eb-9426-fe7f47d2670d.png)

Thanks!

**Comment by Lioscro** [comment]
Hi, @cpcouturier,
I don't think this is related to `ulimit` because dynast temporarily increases the maximum number of open file descriptors to the maximum allowed by the OS. The interplay between ulimit, limitBAMsortRAM, and the amount of required memory is a bit confusing, but here is an issue in the STAR github repo that sheds some light: https://github.com/alexdobin/STAR/issues/457#issuecomment-601990866

Some key points are that higher outBAMsortingBinsN reduces memory requirements because the BAM sorting is done per bin and merged. The value automatically calculated should be pretty close to the maximum that your system can support. You can always override any STAR argument using the `--STAR-overrides` argument. For instance, you may want to provide `--limitBAMsortRAM` to the value that STAR is suggesting like so.
```
dynast align ... --STAR-overrides="--limitBAMsortRAM 101537264536"
```
Note that the overrides should be in quotes so that it doesn't get interpreted as dynast arguments.

**Comment by Lioscro** [comment]
The shell you are running dynast on is interpreting the double quotes as part of the argument. I've just pushed an update to strip quotes from the string, so I think it should work after you install the newest version.

**Comment by cpcouturier** [comment]
Awesome! Thank you @Lioscro! I reduced BinsN and increased sortRAM in separate runs - both worked. 

Worth saying that locally (MacBook Pro), ulimit -Hn was set to unlimited (which came up to max 96bit) by default. It was trying to run it with hundreds of millions of bins which made it crash with a memory error. Adjusting ulimit -Hn to something reasonable (20 000 or so) had worked since I believe this value is used as input to decide the number of bins in your code.
