### ISSUE TITLE
Dynast count error: 

### ISSUE THREAD

**Issue by mav-mit** [aristoteleo/dynast-release#6]
Despite using Dynast Count on the same data there seems to be a difference when running Dynast with "TC, GA ", "GA", and "TC". It seems that there's in increase in the conversion you call for. (ie. Higher TC when you look for TC)

[210809_dual_labeling.pdf](https://github.com/aristoteleo/dynast-release/files/6985065/210809_dual_labeling.pdf)

**Comment by Lioscro** [comment]
Hi, @martinavillanueva,
What exactly are you plotting here?
Are these the mutation rates?

**Comment by Xiaojieqiu** [comment]
Thanks! My understanding is that when Martin calls for TC,GA  (with `--conversion TC,GA` argument in dynast count), the TC, GA mutation rates are different from when you call for TC or GA separately (with `--conversion TC` or `--conversion GA` argument in dynast count). And when calling for TC or GA, the corresponding TC/GA mutation rate is higher than when you don't look for it. Is any special treatment for the mutation you asked for (via `---conversion`) comparing the rest mutations?

**Comment by martinavillanueva** [comment]
Exactly @Xiaojieqiu! Does that make sense @Lioscro ?

**Comment by martinavillanueva** [comment]
Take a look at GA conversion and how it it lower when we don't look for the conversion (last slide) vs when we do look for it (the top 2 slides)

[210809_dual_labeling.pdf](https://github.com/aristoteleo/dynast-release/files/6992854/210809_dual_labeling.pdf)

**Comment by Lioscro** [comment]
I see what you mean. This is because in the UMI deduplication step, which read is selected depends on the number of conversions (see my previous comment). When you supply `--conversion TC,GA`, the read with the most TC+GA conversions is selected; when you supply `--conversion GA`, the read with the most GA conversions is selected; and vice-versa when you supply `--conversion TC`.

Does that make sense?

**Comment by martinavillanueva** [comment]
I see. And so the reason we see changes in other conversions (see blue and yellow circles) is because based on the transcripts that were selected to have the conversion of interest, it changes the background. Is that right? 


Would you expect this to affect the accuracy of calling new / old transcripts? 
[210809_dual_labeling_2.pdf](https://github.com/aristoteleo/dynast-release/files/7034304/210809_dual_labeling_2.pdf)
